# Generated by Django 5.1.4 on 2025-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('IP', 'In-Progress'), ('C', 'Completed')], default='P', max_length=2)),
            ],
        ),
    ]
